AWSTemplateFormatVersion: 2010-09-09
Description: >-
  (Forntend) Empty S3 bucket with static website hosting enabled.
Mappings:
  Region2S3WebsiteSuffix:
    us-east-1:
      Suffix: .s3-website-us-east-1.amazonaws.com
    us-west-1:
      Suffix: .s3-website-us-west-1.amazonaws.com
    us-west-2:
      Suffix: .s3-website-us-west-2.amazonaws.com
    eu-west-1:
      Suffix: .s3-website-eu-west-1.amazonaws.com
    ap-northeast-1:
      Suffix: .s3-website-ap-northeast-1.amazonaws.com
    ap-northeast-2:
      Suffix: .s3-website-ap-northeast-2.amazonaws.com
    ap-southeast-1:
      Suffix: .s3-website-ap-southeast-1.amazonaws.com
    ap-southeast-2:
      Suffix: .s3-website-ap-southeast-2.amazonaws.com
    ap-south-1:
      Suffix: .s3-website-ap-south-1.amazonaws.com
    us-east-2:
      Suffix: .s3-website-us-east-2.amazonaws.com
    sa-east-1:
      Suffix: .s3-website-sa-east-1.amazonaws.com
    cn-north-1:
      Suffix: .s3-website.cn-north-1.amazonaws.com.cn
    eu-central-1:
      Suffix: .s3-website.eu-central-1.amazonaws.com
Resources:
  S3BucketForWebsiteContent:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
            - '*'
            AllowedMethods:
            - GET
            - POST
            AllowedOrigins:
            - '*'
      WebsiteConfiguration:
        IndexDocument: index.html

  SampleBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3BucketForWebsiteContent
      PolicyDocument:
        Statement:
          - Action:
            - 's3:*'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3BucketForWebsiteContent
                - /*
            Principal: '*'

  # CfnDistribution:
  #   Type: AWS::CloudFront::Distribution
  #   Properties:
  #     DistributionConfig:
  #       Comment: CDN for S3-backed website
  #       Enabled: 'true'
  #       DefaultCacheBehavior:
  #         ForwardedValues:
  #           QueryString: 'true'
  #         TargetOriginId: only-origin
  #         ViewerProtocolPolicy: allow-all
  #       DefaultRootObject: index.html
  #       Origins:
  #       - CustomOriginConfig:
  #           HTTPPort: '80'
  #           HTTPSPort: '443'
  #           OriginProtocolPolicy: http-only
  #         DomainName: !Join ['', [!Ref 'S3BucketForWebsiteContent', !FindInMap [Region2S3WebsiteSuffix,
  #               !Ref 'AWS::Region', Suffix]]]
  #         Id: only-origin

Outputs:
  BucketName:
    Value:
      Ref: S3BucketForWebsiteContent
    Description: Name of S3 bucket to hold website content
